stages:
  - lint
  - test
  - build
  - push

variables:
  DOCKER_IMAGE: "tinyops/multiverse-bot"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - export APP_VERSION=$(grep 'const Version = ' cmd/bot/main.go | cut -d'"' -f2)

test:
  stage: test
  image: golang:1.26-alpine
  script:
    - go test -v -race ./...
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/golangci-lint
      - .go/pkg/mod

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --progress=plain --platform=linux/amd64 -t $DOCKER_IMAGE:$APP_VERSION .
    - docker push $DOCKER_IMAGE:$APP_VERSION
  dependencies:
    - lint
    - test
  tags:
    - docker
